var Constants = {
	BROW_SEGMENTS_MIN_MAX: {min: 1, max: 10},
	BROW_SIZE_MIN_MAX: {min: 6, max: 18},
	DEFAULT_END_ANGLE: 360,
	DEFAULT_START_ANGLE: 0,
	EAR_HEIGHT_MIN_MAX: {min: 10, max: 20},
	EAR_SEGMENTS_MIN_MAX: {min: 3, max: 10},
	EAR_WIDTH_MIN_MAX: {min: 2, max: 5},
	EYE_SEGMENTS_MIN_MAX: {min: 1, max: 10},
	EYE_SIZE_MIN_MAX: {min: 6, max: 18},
	EYE_SPACING_MIN_MAX: {min: 0, max: 10},
	HAIR_SEGMENTS_MIN_MAX: {min: 20, max: 80},
	HEAD_HEIGHT: 100,
	HEAD_SEGMENTS_MIN_MAX: {min: 10, max: 30},
	HEAD_WIDTH_MIN_MAX: {min: 30, max: 80},
	MOUTH_END_ANGLE_MIN_MAX: {min: 360, max: 1000},
	MOUTH_HEIGHT_MIN_MAX: {min: 1, max: 5},
	MOUTH_SEGMENTS_MIN_MAX: {min: 6, max: 15},
	MOUTH_START_ANGLE_MIN_MAX: {min: 0, max: 360},
	MOUTH_WIDTH_MIN_MAX: {min: 10, max: 25},
	NOSE_END_ANGLE_MIN_MAX: {min: 0, max: 90},
	NOSE_SEGMENTS_MIN_MAX: {min: 1, max: 5},
	NOSE_SIZE_MIN_MAX: {min: 6, max: 18},
	NOSE_START_ANGLE_MIN_MAX: {min: -90, max: 0},
	PUPIL_SEGMENTS_MIN_MAX: {min: 1, max: 100},
	PUPIL_SIZE_MIN_MAX: {min: 1, max: 5},
	RANDOMIZER_MIN_MAX: {min: 10, max: 50}
}